service: nucleus-backend
plugins:
  - serverless-offline-sqs
  - serverless-offline

provider:
  name: aws

custom:
  serverless-offline-sqs:
    autoCreate: true
    endpoint: http://0.0.0.0:9324

resources:
  Resources:
    Queue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: Queue.fifo

functions:
  graphql:
    events:
      - http:
          cors: true
          method: get
          path: graphql
      - http:
          cors: true
          method: post
          path: graphql
    handler: dist/graphql/index.graphqlHandler
  queue:
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - Queue
              - Arn
    handler: dist/queue/index.queueHandler
