functions:
  graphql:
    events:
      - http:
          cors: true
          method: get
          path: graphql
      - http:
          cors: true
          method: post
          path: graphql
    handler: dist/graphql/index.graphqlHandler
plugins:
  - serverless-offline
provider:
  environment:
    DN_PASSWORD: ${env:DN_PASSWORD}
    DN_USERNAME: JLeckenbySDH
    TYPEORM_HOST: nucleus-backend-depotnet-poc.cxpjhjwyl9xj.eu-west-2.rds.amazonaws.com
    TYPEORM_PASSWORD: ${env:TYPEORM_PASSWORD}
  name: aws
  region: eu-west-2
  runtime: nodejs12.x
  timeout: 30
service: nucleus-backend-depotnet-poc
