service: nucleus-backend
plugins:
  - serverless-offline

provider:
  name: aws

functions:
  graphql:
    events:
      - http:
          cors: true
          method: get
          path: graphql
      - http:
          cors: true
          method: post
          path: graphql
    handler: dist/graphql/index.graphqlHandler
