service: nucleus-backend
plugins:
  - serverless-offline

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs12.x
  timeout: 30

functions:
  graphql:
    events:
      - http:
          cors: true
          method: get
          path: graphql
      - http:
          cors: true
          method: post
          path: graphql
    handler: dist/graphql/index.graphqlHandler
