service: nucleus-backend
plugins:
  - serverless-offline
  - serverless-offline-sqs
  - serverless-s3-local

provider:
  name: aws

custom:
  s3:
    cors: cors.xml

functions:
  graphql:
    events:
      - http:
          cors: true
          method: get
          path: graphql
      - http:
          cors: true
          method: post
          path: graphql
    handler: dist/graphql/index.graphqlHandler

resources:
  Resources:
    Queue:
      Type: AWS::SQS::Queue
    Uploads:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: uploads.localhost
