export { AuthResolver } from "./auth/auth.resolver";
export { AddressLookupResolver } from "./address-lookup/address-lookup.resolver";
export { IdentificationResolver } from "./identification/identification.resolver";
export { OperativeResolver } from "./operative/operative.resolver";
export { SubcontractorResolver } from "./subcontractor/subcontractor.resolver";
export { UploadResolver } from "./upload/upload.resolver";
export { UserResolver } from "./user/user.resolver";
export { WorkPackResolver } from "./work-pack/work-pack.resolver";
export { WorkstreamResolver } from "./workstream/workstream.resolver";
