name: Deploy
on:
  push:
    branches:
      - develop
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: "Retrieve code"
        uses: actions/checkout@v2

      - name: Install modules
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: yarn test

  build:
    name: Build Bundles
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: "Retrieve code"
        uses: actions/checkout@v2

      - name: Install modules
        uses: bahmutov/npm-install@v1

      - name: Build backend
        run: yarn workspace @sdh-project-services/nucleus-backend build

      - name: Build UI
        run: yarn workspace @sdh-project-services/nucleus-ui build

      - name: Build frontend
        run: yarn workspace @sdh-project-services/nucleus-frontend build

  storybook:
    name: Publish Storybook
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: "Retrieve code"
        uses: actions/checkout@v2

      - name: Install modules
        uses: bahmutov/npm-install@v1

      - name: Publish storybook
        run: cd packages/nucleus-ui && yarn chromatic
          --exit-once-uploaded
          --project-token=${{ secrets.CHROMATIC }}
