name: jest
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Retrieve code"
        uses: actions/checkout@v2

      - name: Install modules using yarn
        run: yarn

      - name: Run tests
        run: yarn workspaces run test
